spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/storekeeper
    username: storekeeper
    password: storekeeper
  sql:
    init:
      mode: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  properties:
    hibernate: org.hibernate.dialect.PostgreSQLDialect